version: '3.4'

services:
  abouttokens:
    image: ${DOCKER_REGISTRY-}abouttokens
    build:
      context: .
      dockerfile: AboutTokens/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile

