version: '3.4'

services:
  abouttokens:
    image: abouttokens:latest
    # build:
    #   context: .
    #   dockerfile: AboutTokens/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile

